<template>
  <div class="page-container">
    <PatientSelector v-model="selectedPatient" @selected="handlePatientSelected" />
    <div class="page-header"><h2 class="page-title">改善方案管理</h2><el-button type="primary" @click="handleAdd"><el-icon><Plus /></el-icon>添加方案</el-button></div>
    <el-card class="search-card"><el-form :inline="true" :model="searchForm"><el-form-item label="患者"><el-select v-model="searchForm.userId" placeholder="请选择患者" clearable filterable style="width: 240px"><el-option v-for="patient in patientOptions" :key="patient.id" :label="patient.name + ' (' + patient.phone + ')'" :value="patient.id" /></el-select></el-form-item><el-form-item label="状态"><el-select v-model="searchForm.status" placeholder="全部状态" clearable style="width: 140px"><el-option label="进行中" value="active" /><el-option label="已完成" value="completed" /></el-select></el-form-item><el-form-item><el-button type="primary" @click="handleSearch"><el-icon><Search /></el-icon>搜索</el-button><el-button @click="resetSearch"><el-icon><Refresh /></el-icon>重置</el-button></el-form-item></el-form></el-card>
    <el-card><el-table :data="tableData" v-loading="loading" border stripe><el-table-column label="患者" width="120" fixed><template #default="{ row }">{{ getPatientName(row.userId) }}</template></el-table-column><el-table-column prop="planName" label="方案名称" min-width="150" /><el-table-column prop="healthScore" label="健康评分" width="100" /><el-table-column prop="riskLevel" label="风险等级" width="100" /><el-table-column prop="status" label="状态" width="100"><template #default="{ row }"><el-tag :type="row.status === 'completed' ? 'success' : 'warning'">{{ statusText(row.status) }}</el-tag></template></el-table-column><el-table-column prop="startDate" label="开始日期" width="120" /><el-table-column prop="endDate" label="结束日期" width="120" /><el-table-column prop="abnormalIndicators" label="异常指标" min-width="180" show-overflow-tooltip /><el-table-column label="操作" width="190" fixed="right"><template #default="{ row }"><el-button v-if="row.status !== 'completed'" type="success" link @click="completeRow(row)">完成</el-button><el-button type="primary" link @click="editRow(row)">编辑</el-button><el-button type="danger" link @click="deleteRow(row)">删除</el-button></template></el-table-column></el-table><div class="pagination-wrap"><el-pagination v-model:current-page="pagination.page" v-model:page-size="pagination.size" :total="pagination.total" :page-sizes="[10, 20, 50, 100]" layout="total, sizes, prev, pager, next, jumper" @size-change="handleSizeChange" @current-change="fetchData" /></div></el-card>
    <el-dialog v-model="dialogVisible" :title="dialogTitle" width="760px" :close-on-click-modal="false"><el-form :model="formData" label-width="125px"><el-row :gutter="20"><el-col :span="12"><el-form-item label="患者" required><el-select v-model="formData.userId" filterable style="width: 100%"><el-option v-for="patient in patientOptions" :key="patient.id" :label="patient.name + ' (' + patient.phone + ')'" :value="patient.id" /></el-select></el-form-item></el-col><el-col :span="12"><el-form-item label="方案名称" required><el-input v-model="formData.planName" /></el-form-item></el-col></el-row><el-row :gutter="20"><el-col :span="12"><el-form-item label="健康评分"><el-input-number v-model="formData.healthScore" :min="0" :max="100" /></el-form-item></el-col><el-col :span="12"><el-form-item label="风险等级"><el-input v-model="formData.riskLevel" /></el-form-item></el-col></el-row><el-form-item label="异常指标"><el-input v-model="formData.abnormalIndicators" /></el-form-item><el-form-item label="饮食计划"><el-input v-model="formData.dietPlan" type="textarea" :rows="2" /></el-form-item><el-form-item label="饮水控制计划"><el-input v-model="formData.waterControlPlan" type="textarea" :rows="2" /></el-form-item><el-form-item label="生活方式建议"><el-input v-model="formData.lifestyleSuggestions" type="textarea" :rows="2" /></el-form-item><el-form-item label="用药调整"><el-input v-model="formData.medicationAdjustments" type="textarea" :rows="2" /></el-form-item><el-form-item label="随访备注"><el-input v-model="formData.followUpNotes" type="textarea" :rows="2" /></el-form-item><el-row :gutter="20"><el-col :span="12"><el-form-item label="开始日期"><el-date-picker v-model="formData.startDate" type="date" value-format="YYYY-MM-DD" style="width: 100%" /></el-form-item></el-col><el-col :span="12"><el-form-item label="结束日期"><el-date-picker v-model="formData.endDate" type="date" value-format="YYYY-MM-DD" style="width: 100%" /></el-form-item></el-col></el-row></el-form><template #footer><el-button @click="dialogVisible = false">取消</el-button><el-button type="primary" @click="handleSave">保存</el-button></template></el-dialog>
  </div>
</template>

<script setup>
import { ref, reactive, onMounted } from 'vue'
import { Plus, Search, Refresh } from '@element-plus/icons-vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import request from '@/utils/request'
import PatientSelector from '@/components/PatientSelector.vue'
const loading = ref(false), dialogVisible = ref(false), dialogTitle = ref('添加改善方案'), patientOptions = ref([]), tableData = ref([]), selectedPatient = ref(null)
const searchForm = reactive({ userId: '', status: '' }), pagination = reactive({ page: 1, size: 10, total: 0 })
const emptyForm = () => ({ id: '', userId: '', planName: '', healthScore: null, abnormalIndicators: '', dietPlan: '', waterControlPlan: '', lifestyleSuggestions: '', medicationAdjustments: '', followUpNotes: '', riskLevel: '', status: 'active', startDate: '', endDate: '' })
const formData = reactive(emptyForm())
const unwrapList = (data) => data?.content || data?.list || (Array.isArray(data) ? data : [])
const fetchData = async () => { if (!searchForm.userId) return; loading.value = true; try { const filters = { page: pagination.page, size: pagination.size, userId: searchForm.userId }; if (searchForm.status) filters.status = searchForm.status; const res = await request.get('/improvement-plan/admin/list', { params: filters }); if (res.code === 200) { tableData.value = unwrapList(res.data); pagination.total = res.data?.totalElements || res.data?.total || tableData.value.length } } catch { ElMessage.error('获取方案列表失败') } finally { loading.value = false } }
const fetchPatients = async () => { try { const res = await request.get('/user/list', { params: { page: 1, size: 100 } }); if (res.code === 200) patientOptions.value = unwrapList(res.data) } catch { ElMessage.error('获取患者列表失败') } }
const handleSearch = () => { pagination.page = 1; fetchData() }, handlePatientSelected = (patient) => { searchForm.userId = patient.id; pagination.page = 1; tableData.value = []; pagination.total = 0; fetchData() }, handlePatientChange = () => { pagination.page = 1; tableData.value = []; pagination.total = 0; fetchData() }, resetSearch = () => { searchForm.userId = ''; searchForm.status = ''; tableData.value = []; pagination.total = 0 }, handleSizeChange = (size) => { pagination.size = size; pagination.page = 1; fetchData() }
const handleAdd = () => { if (!searchForm.userId) return ElMessage.warning('请先选择患者'); Object.assign(formData, emptyForm(), { userId: searchForm.userId }); dialogTitle.value = '添加改善方案'; dialogVisible.value = true }, editRow = (row) => { Object.assign(formData, emptyForm(), row); dialogTitle.value = '编辑改善方案'; dialogVisible.value = true }
const handleSave = async () => { if (!formData.userId || !formData.planName) return ElMessage.warning('请选择患者并填写方案名称'); try { const res = formData.id ? await request.put(`/improvement-plan/admin/${formData.id}`, formData) : await request.post('/improvement-plan/admin', formData); if (res.code === 200) { ElMessage.success('保存成功'); dialogVisible.value = false; fetchData() } } catch { ElMessage.error('保存失败') } }
const completeRow = async (row) => { try { await ElMessageBox.confirm('确定将该方案标记为已完成吗？', '提示', { type: 'warning' }); const res = await request.put(`/improvement-plan/admin/${row.id}/complete`); if (res.code === 200) { ElMessage.success('方案已完成'); fetchData() } } catch (error) { if (error !== 'cancel') ElMessage.error('完成方案失败') } }
const deleteRow = async (row) => { try { await ElMessageBox.confirm('确定要删除该改善方案吗？', '提示', { type: 'warning' }); const res = await request.delete(`/improvement-plan/admin/${row.id}`); if (res.code === 200) { ElMessage.success('删除成功'); fetchData() } } catch (error) { if (error !== 'cancel') ElMessage.error('删除失败') } }
const getPatientName = (id) => patientOptions.value.find(p => p.id === id)?.name || id || '-', statusText = (status) => status === 'completed' ? '已完成' : '进行中'
onMounted(() => { fetchPatients() })
</script>

<style scoped>
.page-container { padding: 20px; }.page-header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 20px; }.page-title { margin: 0; font-size: 20px; color: #303133; }.search-card { margin-bottom: 20px; }.pagination-wrap { display: flex; justify-content: flex-end; margin-top: 20px; }
</style>
